services:
#  bot:
#    build: .
#    ports:
#      - "8001:8000"  # Порт для вебхуков
#    environment:
#      - BOT_TOKEN=7978079024:AAEMjRp68zWXbLtV5W4zjqcXQfEyQCzTAwI
#      - WEBHOOK_URL=https://d80vzq-188-162-12-160.ru.tuna.am/webhook
#    depends_on:
#      - db
#    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_postg-db-1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_postg-db-1"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db


  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://root:12345@db:5432/test_postg-db-1?client_encoding=utf8
    volumes:
      - .:/app

volumes:
  postgres_data: