"""init

Revision ID: fc2977231b45
Revises: 
Create Date: 2025-04-03 02:51:35.743594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2977231b45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departaments', ['depart_id'])
    op.create_unique_constraint(None, 'groups', ['group_id'])
    op.create_unique_constraint(None, 'services', ['service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'departaments', type_='unique')
    # ### end Alembic commands ###
